# run.R -- replication of "Natural Resources and Economic Growth: A Meta-Analysis"
# (Havranek, Horvath & Zeynalov, World Development 88, 2016), Table 3, "Tests of the true
# effect and publication selection".
#
# Author code, published in full at site/resource_curse/resource_curse.do:
#   164  eststo: reg PCC PCC_SE [pweight=prec], cluster (ID)                -> Panel A col 1
#   165  eststo: ivreg PCC (PCC_SE=instrument) [pweight=prec], cluster(ID)  -> Panel A col 2
#   166  eststo: xtreg TSTAT INVSE, fe vce(cluster ID)                      -> Panel B col 1
#   167  eststo: xtmixed PCC PCC_SE || ID: [pweight=prec]                   -> Panel B col 2
#
# Panel A is estimated without clustering, and that needs saying because the table note says
# otherwise. The note reads "The standard errors of the regression parameters are clustered at
# the study level", and the do-file lines above carry `cluster (ID)`. Run that way the
# coefficients reproduce exactly and every printed t-statistic misses by roughly a factor of
# three: on the site's data in Stata 15.1 the OLS standard-error row gives t = -1.73 against a
# printed -5.18, and the IV row t = -1.74 against -4.81. Plain heteroskedasticity-robust
# standard errors, which is what `[pweight=]` alone produces in Stata, reproduce the printed
# values exactly: -5.18 and -4.81, and the printed F = 26.87 is (-5.1834)^2 to five digits.
#
# The authors' own log of the published run settles it. The regressions that produced Table 3
# carry no `cluster` option,
#     . eststo: reg PCC PCC_SE [pweight=prec]
#     . eststo: ivreg PCC (PCC_SE=instrument) [pweight=prec]
# and the log prints -1.016527 (.196112) t = -5.18, 0.0260833 (.0162477), N = 605 and
# F(1,603) = 26.87, which are the printed cells. Panel B's fixed-effects column IS clustered
# and matches exactly, so the two panels differ whatever the shared note says. This package
# follows the estimation that produced the table. It reads nothing but the site's published CSV.
#
# COEFFICIENT CELLS: the paper TRUNCATES coefficients to three decimals instead of rounding.
# The authors' esttab output for the same regressions (table3.tex, generated by line 169 of the
# do-file) prints -1.017, -1.235 and 0.039, correctly rounded; the paper's Table 3 prints
# -1.016, -1.234 and 0.038. Every coefficient cell that distinguishes the two rules goes the
# truncation way, in Table 3 (-1.016527 -> -1.016; -1.234917 -> -1.234; 0.0386915 -> 0.038) and
# again in the appendix Table A.1 Panel C (-0.15788 -> -0.157; 0.30884 -> 0.308). None goes the
# other way. The t-statistics and p-values are copied from Stata's own rounded display and so
# round normally. The exact estimates are reported here unaltered, so those three cells fail a
# round-to-3-decimals check by construction; that is a property of the paper's typesetting, not
# of the estimation, and is not something a replication can or should reproduce.
#
# PANEL B col 1: the same precision-weighted PCC-on-PCC_SE regression estimated at the study
# level. xtreg takes no pweight, so the do-file uses the standard workaround (lines 43-44:
# INVSE = 1/PCC_SE, TSTAT = PCC/PCC_SE): dividing PCC = b0 + b1*PCC_SE + e through by PCC_SE
# gives TSTAT = b0*INVSE + b1 + e/PCC_SE, so an UNWEIGHTED regression of TSTAT on INVSE
# recovers the 1/SE^2-weighted coefficients. INVSE's slope is the SE (publication-selection)
# row and the reported _cons is the Constant (true-effect) row. All six cells reproduce.
#
# PANEL B col 2: `xtmixed PCC PCC_SE || ID: [pweight=prec]` -- a random-intercept model with
# Stata SAMPLING weights at level 1, which is a different object from lmer's precision weights
# (see the long note on st_xtmixed_pw in stata_compat.R). Five of its six printed cells
# reproduce; the sixth is a sign error in the paper, documented at the call site below.
#
# Uses ONLY the wrappers in stata_compat.R. No feols/lm/rma/lmer/plm/ivreg/quantile call
# anywhere in this file.

if (file.exists("stata_compat.R")) source("stata_compat.R") else
  source("https://meta-analysis.cz/resource_curse/replication/stata_compat.R")

suppressMessages(library(jsonlite))

# ---------------------------------------------------------------------- data
# The published file mirrors the authors' own: same columns, same names, including the
# already-constructed PCC, PCC_SE, DF and "instrument" columns (resource_curse.do lines 18-35),
# so they are read directly rather than rebuilt. (Rebuilding PCC/PCC_SE/prec from EFFECT_SIZE
# per lines 18-29 changes nothing past the seventh digit -- checked. The CSV and the site's
# .dta agree to 6e-5 on prec, which is float storage.)
d <- read.csv(
  (if (file.exists("resource_curse.csv")) "resource_curse.csv" else
     "https://meta-analysis.cz/data/v1/resource_curse/resource_curse.csv"),
  stringsAsFactors = FALSE
)

n_base <- nrow(d)
n_groups <- length(unique(d$ID))
cat(sprintf("N = %d, study groups (ID) = %d\n", n_base, n_groups))

results <- list()
add <- function(label, value) results[[label]] <<- as.numeric(value)

add("Panel A: N (OLS)", n_base)
add("Panel A: N (IV)", n_base)
add("Panel B: N (FE)", n_base)
add("Panel B: N (Mixed)", n_base)
add("Panel B: groups (FE)", n_groups)
add("Panel B: groups (Mixed)", n_groups)

# ----------------------------------------------------- Panel A, col 1: "Clustered OLS"
# reg PCC PCC_SE [pweight=prec] -- heteroskedasticity-robust, NOT clustered; see the header.
# Stata's regress small-sample convention (V * N/(N-K), t(N-K)) is st_regress's default.
m_ols <- st_regress(PCC ~ PCC_SE, data = d, weights = ~prec, robust = TRUE)
ct_ols <- fixest::coeftable(m_ols)
add("Panel A: OLS SE (publication selection) coef", ct_ols["PCC_SE", "Estimate"])
add("Panel A: OLS SE (publication selection) t",    ct_ols["PCC_SE", "t value"])
add("Panel A: OLS SE (publication selection) p",    ct_ols["PCC_SE", "Pr(>|t|)"])
add("Panel A: OLS Constant (true effect) coef",     ct_ols["(Intercept)", "Estimate"])
add("Panel A: OLS Constant (true effect) t",        ct_ols["(Intercept)", "t value"])
add("Panel A: OLS Constant (true effect) p",        ct_ols["(Intercept)", "Pr(>|t|)"])

# ----------------------------------------------------- Panel A, col 2: IV estimation
# ivreg PCC (PCC_SE=instrument) [pweight=prec] -- PCC_SE instrumented by "instrument"
# = 1/sqrt(DF) (do-file line 35), weighted by prec, heteroskedasticity-robust.
#
# SMALL-SAMPLE CONVENTION: `ivreg` is the old Stata command (retired in Stata 10) and reports
# regress-style statistics -- robust VCE multiplied by N/(N-K), inference against t(N-K) --
# whereas `ivreg2` without `small`, the profile st_ivreg2() implements, is large-sample z.
# The two differ here in the second decimal of the printed t: large-sample gives -4.82 / 2.42,
# the paper prints -4.81 / 2.41, and `ivreg` gives -4.808 / 2.412. Confirmed on Stata 15.1:
# `ivregress 2sls PCC (PCC_SE=instrument) [pweight=prec], small` returns exactly
# -1.234917 (.25686) t = -4.81 and .0386915 (.0160392) t = 2.41, the printed cells, and the
# authors' log shows the same for `ivreg`. st_ivreg2() refuses `small = TRUE` by design, so the
# N/(N-K) factor is applied to its output here; it is the documented Stata adjustment for the
# command the authors ran, not a fitted constant, and it leaves the point estimates untouched.
# st_ivreg2() also has no `robust=` argument, so a cluster-per-observation call is used --
# with one observation per cluster the cluster sandwich IS the heteroskedasticity-robust
# sandwich, algebraically.
d$.rowid <- seq_len(nrow(d))
m_iv <- st_ivreg2(PCC ~ 1 | PCC_SE ~ instrument, data = d, weights = ~prec, cluster = ~.rowid)
co_iv <- st_coefs(m_iv, z = TRUE)
K_iv  <- length(stats::coef(m_iv))
N_iv  <- stats::nobs(m_iv)
ivreg_adj <- sqrt(N_iv / (N_iv - K_iv))      # Stata `ivreg` / `regress` robust: V * N/(N-K)
co_iv$statistic <- co_iv$statistic / ivreg_adj
co_iv$p.value   <- 2 * stats::pt(-abs(co_iv$statistic), df = N_iv - K_iv)
cat(sprintf("IV: old-Stata `ivreg` small-sample profile applied: SE x sqrt(%d/%d), t(%d) p-values\n",
            N_iv, N_iv - K_iv, N_iv - K_iv))
add("Panel A: IV SE (publication selection) coef", co_iv$estimate[co_iv$term == "fit_PCC_SE"])
add("Panel A: IV SE (publication selection) t",     co_iv$statistic[co_iv$term == "fit_PCC_SE"])
add("Panel A: IV SE (publication selection) p",     co_iv$p.value[co_iv$term == "fit_PCC_SE"])
add("Panel A: IV Constant (true effect) coef",      co_iv$estimate[co_iv$term == "(Intercept)"])
add("Panel A: IV Constant (true effect) t",         co_iv$statistic[co_iv$term == "(Intercept)"])
add("Panel A: IV Constant (true effect) p",         co_iv$p.value[co_iv$term == "(Intercept)"])

# ---- Panel A under the specification the table note describes ------------------------------
# The note to Table 3 says the standard errors are clustered at the study level, and the
# do-file lines carry `cluster (ID)`. The published table was produced without that option
# (see the header). Both are reported here so a reader can see either: the values above
# reproduce the table as printed, the values below are what clustering by study gives.
# Coefficients are identical under both; only the standard errors, t-statistics and p-values
# change.
m_ols_cl <- st_regress(PCC ~ PCC_SE, data = d, weights = ~prec, cluster = ~ID)
ct_ols_cl <- st_coefs(m_ols_cl, z = FALSE)
m_iv_cl <- st_ivreg2(PCC ~ 1 | PCC_SE ~ instrument, data = d, weights = ~prec, cluster = ~ID)
co_iv_cl <- st_coefs(m_iv_cl, z = TRUE)
# fixest labels an instrumented regressor "fit_<name>"; match either form
.se_row <- co_iv_cl$term %in% c("PCC_SE", "fit_PCC_SE")

add("Panel A clustered by study: OLS SE coef",  ct_ols_cl$estimate[ct_ols_cl$term == "PCC_SE"])
add("Panel A clustered by study: OLS SE t",     ct_ols_cl$statistic[ct_ols_cl$term == "PCC_SE"])
add("Panel A clustered by study: OLS SE p",     2 * stats::pt(-abs(ct_ols_cl$statistic[ct_ols_cl$term == "PCC_SE"]), df = n_groups - 1))
add("Panel A clustered by study: OLS Constant coef", ct_ols_cl$estimate[ct_ols_cl$term == "(Intercept)"])
add("Panel A clustered by study: OLS Constant t",    ct_ols_cl$statistic[ct_ols_cl$term == "(Intercept)"])
add("Panel A clustered by study: OLS Constant p",    2 * stats::pt(-abs(ct_ols_cl$statistic[ct_ols_cl$term == "(Intercept)"]), df = n_groups - 1))
add("Panel A clustered by study: IV SE coef",   co_iv_cl$estimate[.se_row])
add("Panel A clustered by study: IV SE t",      co_iv_cl$statistic[.se_row])
add("Panel A clustered by study: IV Constant coef", co_iv_cl$estimate[co_iv_cl$term == "(Intercept)"])
add("Panel A clustered by study: IV Constant t",    co_iv_cl$statistic[co_iv_cl$term == "(Intercept)"])

cat(sprintf("Panel A, clustered by study (the table note's specification):
"))
cat(sprintf("  OLS  SE-term  coef %.6f  t %.3f  p %.4f
",
            ct_ols_cl$estimate[ct_ols_cl$term == "PCC_SE"],
            ct_ols_cl$statistic[ct_ols_cl$term == "PCC_SE"],
            2 * stats::pt(-abs(ct_ols_cl$statistic[ct_ols_cl$term == "PCC_SE"]), df = n_groups - 1)))
cat(sprintf("  OLS  constant coef %.6f  t %.3f  p %.4f
",
            ct_ols_cl$estimate[ct_ols_cl$term == "(Intercept)"],
            ct_ols_cl$statistic[ct_ols_cl$term == "(Intercept)"],
            2 * stats::pt(-abs(ct_ols_cl$statistic[ct_ols_cl$term == "(Intercept)"]), df = n_groups - 1)))
cat(sprintf("  IV   SE-term  coef %.6f  t %.3f
",
            co_iv_cl$estimate[.se_row],
            co_iv_cl$statistic[.se_row]))

# ----------------------------------------------------- Panel B, col 1: Fixed effects
# xtreg TSTAT INVSE, fe vce(cluster ID) -- see the header on the SE-divided variables.
m_fe <- st_xtreg_fe(TSTAT ~ INVSE, data = d, panel = "ID", cluster = ~ID)
ct_fe <- fixest::coeftable(m_fe)
m_fe_cons <- st_xtreg_fe_cons("TSTAT", "INVSE", "ID", d, cluster = ~ID)
ct_fe_cons <- fixest::coeftable(m_fe_cons)
add("Panel B: FE SE (publication bias) coef",       ct_fe["INVSE", "Estimate"])
add("Panel B: FE SE (publication bias) t",          ct_fe["INVSE", "t value"])
add("Panel B: FE SE (publication bias) p",          ct_fe["INVSE", "Pr(>|t|)"])
add("Panel B: FE Constant (effect beyond bias) coef", ct_fe_cons["(Intercept)", "Estimate"])
add("Panel B: FE Constant (effect beyond bias) t",    ct_fe_cons["(Intercept)", "t value"])
add("Panel B: FE Constant (effect beyond bias) p",    ct_fe_cons["(Intercept)", "Pr(>|t|)"])

# ----------------------------------------------------- Panel B, col 2: Mixed-effects ML
# xtmixed PCC PCC_SE || ID: [pweight=prec] (do-file line 167). Stata pweights raise each
# conditional density to the power w, which is NOT lmer's precision weight; st_xtmixed_pw()
# maximises that pseudo-likelihood directly and takes the cluster-robust sandwich Stata forces
# under pweights. Reproduces the authors' log to six significant digits -- see the evidence
# table in the wrapper's header comment.
#
# One cell does not match. Table 3 prints the constant as -0.133 with a z-statistic of 1.43 and
# p = 0.153. A positive z does not belong to a negative coefficient, and the authors' own log for
# this regression reads
#     _cons  -.1333425   .0934048   -1.43   0.153
# so the printed z appears to have lost its minus sign in typesetting. This code produces -1.43.
# The target is left at the printed +1.43 and allowed to fail rather than flipped to match.
m_mx <- st_xtmixed_pw(PCC ~ PCC_SE, data = d, group = "ID", weights = "prec")
co_mx <- st_coefs(m_mx, z = TRUE)
cat(sprintf("Mixed (pweighted pseudo-ML): log pL = %.4f, sd(_cons) = %.7f, sd(Residual) = %.7f\n",
            m_mx$loglik, m_mx$sd_u, m_mx$sd_e))
add("Panel B: Mixed SE (publication bias) coef", co_mx$estimate[co_mx$term == "PCC_SE"])
add("Panel B: Mixed SE (publication bias) z",     co_mx$statistic[co_mx$term == "PCC_SE"])
add("Panel B: Mixed SE (publication bias) p",     co_mx$p.value[co_mx$term == "PCC_SE"])
add("Panel B: Mixed Constant (effect beyond bias) coef", co_mx$estimate[co_mx$term == "(Intercept)"])
add("Panel B: Mixed Constant (effect beyond bias) z",     co_mx$statistic[co_mx$term == "(Intercept)"])
add("Panel B: Mixed Constant (effect beyond bias) p",     co_mx$p.value[co_mx$term == "(Intercept)"])

# ------------------------------------------------------------------------------- reporting
cat("\n===== Produced numbers =====\n")
for (nm in names(results)) cat(sprintf("%-50s %s\n", nm, format(results[[nm]], digits = 8)))

write(toJSON(results, auto_unbox = TRUE, digits = 10), file = "results.json")
cat("\nWrote results.json\n")

stata_compat_log()
